In [27]:
import pandas as pd
import numpy as np

In [7]:
DANE=r'Dane\ames2000_NAfix.csv'
dane=pd.read_csv(DANE)
dane.head(10)

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
2,85,RL,60,7200,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,4,2009,WD,Normal,133900
3,90,RL,64,7018,Pave,None,Reg,Bnk,AllPub,Inside,...,0,None,None,None,0,6,2009,WD,Alloca,118858
4,60,RL,111,16259,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,None,None,0,9,2006,New,Partial,342643
5,20,RL,50,4280,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,9,2009,WD,Normal,88750
6,20,RL,155,20064,Pave,None,IR1,Low,AllPub,Inside,...,0,None,None,None,0,5,2007,WD,Normal,279000
7,20,RM,60,7200,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2006,COD,Normal,105000
8,20,RL,70,9100,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,9,2006,WD,Normal,235000
9,70,C (all),None,6449,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,3,2010,WD,Abnorml,93369

In [40]:
dane.dtypes

MS.SubClass        int64
MS.Zoning         object
Lot.Frontage      object
Lot.Area           int64
Street            object
                   ...
Mo.Sold            int64
Yr.Sold            int64
Sale.Type         object
Sale.Condition    object
SalePrice          int64
Length: 80, dtype: object

In [62]:
number=dane.select_dtypes([np.number])
number.count()
non_number = dane.select_dtypes([np.object])
non_number.count()

MS.SubClass        2000
Lot.Area           2000
Overall.Qual       2000
Overall.Cond       2000
Year.Built         2000
Year.Remod.Add     2000
X1st.Flr.SF        2000
X2nd.Flr.SF        2000
Low.Qual.Fin.SF    2000
Gr.Liv.Area        2000
Full.Bath          2000
Half.Bath          2000
Bedroom.AbvGr      2000
Kitchen.AbvGr      2000
TotRms.AbvGrd      2000
Fireplaces         2000
Wood.Deck.SF       2000
Open.Porch.SF      2000
Enclosed.Porch     2000
X3Ssn.Porch        2000
Screen.Porch       2000
Pool.Area          2000
Misc.Val           2000
Mo.Sold            2000
Yr.Sold            2000
SalePrice          2000
dtype: int64

In [13]:
missings = len(dane) - dane.count().sort_values(ascending=True)
missings

Mas.Vnr.Type      16
Bsmt.Exposure      3
Garage.Finish      2
BsmtFin.Type.2     2
Bsmt.Cond          1
                  ..
Exterior.1st       0
Roof.Matl          0
Roof.Style         0
Year.Built         0
SalePrice          0
Length: 80, dtype: int64

In [55]:
dane_copy =dane.copy()
dane_copy.head(2)

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000

In [67]:
def empty_fill(dane):
    for column in dane_copy.columns:
        dane_copy[column] = dane_copy[column].fillna("missing")
     
        return dane_copy
def empty_number(dane):
    
dane_copy

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
2,85,RL,60,7200,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,4,2009,WD,Normal,133900
3,90,RL,64,7018,Pave,None,Reg,Bnk,AllPub,Inside,...,0,None,None,None,0,6,2009,WD,Alloca,118858
4,60,RL,111,16259,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,None,None,0,9,2006,New,Partial,342643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,80,RL,80,8000,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,GdWo,None,0,7,2009,WD,Normal,138000
1996,180,RM,35,3675,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,6,2008,WD,Normal,148000
1997,60,RL,76,10142,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,1,2010,WD,Normal,233000
1998,85,RL,None,7252,Pave,None,IR1,Lvl,AllPub,CulDSac,...,0,None,None,None,0,4,2009,WD,Normal,134900
1999,160,FV,34,2998,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2009,WD,Normal,180000

In [69]:
missings = len(dane_copy) - dane_copy.count().sort_values(ascending=True)
missings

MS.SubClass       0
Garage.Type       0
Fireplace.Qu      0
Fireplaces        0
Functional        0
                 ..
Exterior.2nd      0
Exterior.1st      0
Roof.Matl         0
Sale.Condition    0
SalePrice         0
Length: 80, dtype: int64