In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import FeatureUnion
from sklearn.model_selection import StratifiedKFold

In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV

In [3]:
DANE=r'Dane\ames2000_NAfix.csv'
dane=pd.read_csv(DANE)
dane.head(15)

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
2,85,RL,60,7200,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,4,2009,WD,Normal,133900
3,90,RL,64,7018,Pave,None,Reg,Bnk,AllPub,Inside,...,0,None,None,None,0,6,2009,WD,Alloca,118858
4,60,RL,111,16259,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,None,None,0,9,2006,New,Partial,342643
5,20,RL,50,4280,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,9,2009,WD,Normal,88750
6,20,RL,155,20064,Pave,None,IR1,Low,AllPub,Inside,...,0,None,None,None,0,5,2007,WD,Normal,279000
7,20,RM,60,7200,Pave,Grvl,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2006,COD,Normal,105000
8,20,RL,70,9100,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,9,2006,WD,Normal,235000
9,70,C (all),None,6449,Pave,None,IR1,Lvl,AllPub,Inside,...,0,None,None,None,0,3,2010,WD,Abnorml,93369
10,50,RL,55,7642,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,GdPrv,None,0,6,2007,WD,Normal,189950
11,60,RL,None,28698,Pave,None,IR2,Low,AllPub,CulDSac,...,0,None,None,None,0,6,2009,WD,Abnorml,185000
12,50,RL,51,9839,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,5,2010,WD,Normal,100000
13,80,RL,42,10385,Pave,None,IR1,Lvl,AllPub,CulDSac,...,0,None,None,None,0,4,2006,WD,Normal,174000
14,20,RL,75,8250,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,7,2008,WD,Normal,145000

In [4]:
dane.dtypes # sprawdzamy typy kolumn

MS.SubClass        int64
MS.Zoning         object
Lot.Frontage      object
Lot.Area           int64
Street            object
                   ...
Mo.Sold            int64
Yr.Sold            int64
Sale.Type         object
Sale.Condition    object
SalePrice          int64
Length: 80, dtype: object

In [5]:
column_int = []
column_obj = []
i=0
for typ in dane.dtypes:
    if dane.dtypes[i]=='object':
        column_int.append(dane)
    
    elif dane.dtypes[i]=='int64':
        column_obj.append(dane)
    i+=1

In [6]:
print(len(column_int))
print(len(column_obj))

54
26

In [7]:
#nastepnie sprawdzam ilośc null w danych
number=dane.select_dtypes([np.number])
number.count()
non_number = dane.select_dtypes([np.object])
non_number.count()

MS.Zoning         2000
Lot.Frontage      2000
Street            2000
Alley             2000
Lot.Shape         2000
Land.Contour      2000
Utilities         2000
Lot.Config        2000
Land.Slope        2000
Neighborhood      2000
Condition.1       2000
Condition.2       2000
Bldg.Type         2000
House.Style       2000
Roof.Style        2000
Roof.Matl         2000
Exterior.1st      2000
Exterior.2nd      2000
Mas.Vnr.Type      1984
Mas.Vnr.Area      2000
Exter.Qual        2000
Exter.Cond        2000
Foundation        2000
Bsmt.Qual         1999
Bsmt.Cond         1999
Bsmt.Exposure     1997
BsmtFin.Type.1    1999
BsmtFin.SF.1      2000
BsmtFin.Type.2    1998
BsmtFin.SF.2      2000
Bsmt.Unf.SF       2000
Total.Bsmt.SF     2000
Heating           2000
Heating.QC        2000
Central.Air       2000
Electrical        2000
Bsmt.Full.Bath    2000
Bsmt.Half.Bath    2000
Kitchen.Qual      2000
Functional        2000
Fireplace.Qu      2000
Garage.Type       2000
Garage.Yr.Blt     2000
Garage.Finish     1998
Garage.Cars       2000
Garage.Area       2000
Garage.Qual       1999
Garage.Cond       1999
Paved.Drive       2000
Pool.QC           2000
Fence             2000
Misc.Feature      2000
Sale.Type         2000
Sale.Condition    2000
dtype: int64

In [8]:
missings = len(dane) - dane.count().sort_values(ascending=True)
missings

Mas.Vnr.Type      16
Bsmt.Exposure      3
Garage.Finish      2
BsmtFin.Type.2     2
Bsmt.Cond          1
                  ..
Exterior.1st       0
Roof.Matl          0
Roof.Style         0
Year.Built         0
SalePrice          0
Length: 80, dtype: int64

In [9]:
dane_copy =dane.copy()
dane_copy.head(5)

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000
2,85,RL,60,7200,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,MnPrv,None,0,4,2009,WD,Normal,133900
3,90,RL,64,7018,Pave,None,Reg,Bnk,AllPub,Inside,...,0,None,None,None,0,6,2009,WD,Alloca,118858
4,60,RL,111,16259,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,None,None,0,9,2006,New,Partial,342643

In [10]:
dane_copy= dane.copy()
dane_copy.head(2)

,MS.SubClass,MS.Zoning,Lot.Frontage,Lot.Area,Street,Alley,Lot.Shape,Land.Contour,Utilities,Lot.Config,...,Pool.Area,Pool.QC,Fence,Misc.Feature,Misc.Val,Mo.Sold,Yr.Sold,Sale.Type,Sale.Condition,SalePrice
0,120,RL,34,3901,Pave,None,Reg,Lvl,AllPub,Inside,...,0,None,None,None,0,8,2007,New,Partial,204000
1,20,RL,70,8400,Pave,None,Reg,Lvl,AllPub,Corner,...,0,None,MnPrv,None,0,4,2010,WD,Normal,126000

In [11]:
X = dane_copy.drop(["SalePrice"], axis=1)
y = dane_copy["SalePrice"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [12]:
# Inspired from stackoverflow.com/questions/25239958
class MostFrequentImputer(BaseEstimator, TransformerMixin):
    def fit(self, X, y=None):
        self.most_frequent_ = pd.Series([X[c].value_counts().index[0] for c in X],
                                        index=X.columns)
        return self
    def transform(self, X, y=None):
        return X.fillna(self.most_frequent_)

In [13]:
class DataFrameSelector(BaseEstimator, TransformerMixin):
    def __init__(self, attribute_names):
        self.attribute_names = attribute_names
    def fit(self, X, y=None):
        return self
    def transform(self, X):
        return X[self.attribute_names]

In [18]:
cat_pipeline = Pipeline([
        ("select_cat", DataFrameSelector(column_obj)),
        ("imputer", MostFrequentImputer()),
        ("cat_encoder", OneHotEncoder(sparse=False)),
        ('standardscaler', StandardScaler())
    ])

In [19]:
cat_pipeline.fit_transform(X_train)

array([[-0.78406859, -0.20601527, -0.04634068, ..., -0.12038585,
         0.47756693, -0.30198099],
       [ 1.27539862, -0.20601527, -0.04634068, ..., -0.12038585,
         0.47756693, -0.30198099],
       [ 1.27539862, -0.20601527, -0.04634068, ..., -0.12038585,
        -2.09394732, -0.30198099],
       ...,
       [ 1.27539862, -0.20601527, -0.04634068, ..., -0.12038585,
         0.47756693, -0.30198099],
       [-0.78406859, -0.20601527, -0.04634068, ..., -0.12038585,
         0.47756693, -0.30198099],
       [ 1.27539862, -0.20601527, -0.04634068, ..., -0.12038585,
        -2.09394732,  3.31146674]])

In [ ]:
num_pipeline = Pipeline([
        ("select_numeric", DataFrameSelector(column_int)),
        ("imputer", SimpleImputer(strategy="median")),
        ('standardscaler', StandardScaler())
    ])

In [ ]:
num_pipeline.fit_transform(X_train)

In [ ]:
preprocess_pipeline = FeatureUnion(transformer_list=[
        ("num_pipeline", num_pipeline),
        ("cat_pipeline", cat_pipeline),
    ])

In [ ]:
seed=123
kfold = StratifiedKFold(n_splits=5, random_state=seed)

In [ ]:
from sklearn.linear_model import LogisticRegression

pipe_1 = Pipeline([('preprocessing', preprocess_pipeline), ('classifier', LogisticRegression(C=1))])

param_grid_1 = {
            'classifier__C': [0.001, 0.01, 0.1, 1, 10, 100]
}

grid_1 = GridSearchCV(pipe_1, param_grid_1, cv=kfold, return_train_score=True)

grid_1.fit(X_train, y_train)
#grid_1.best_params_

In [ ]:
from sklearn.linear_model import LogisticRegression
lm = LogisticRegression(max_iter=1000)
lm.fit(X_train, y_train)
print("Test set accuracy: {:.2f}".format(lm.score(X_test, y_test)))